//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int idEntrega { get; set; }
        public int idMueble { get; set; }
        public int idCliente { get; set; }
        public int idPersonal { get; set; }
        public int idPedido { get; set; }
        public string detalles { get; set; }
        public string fechaEntrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mueble Mueble { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
