//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int idEntrega { get; set; }
        public int idMueble { get; set; }
        public int idCliente { get; set; }
        public int idPersonal { get; set; }
        public int idPedido { get; set; }
        public string detalles { get; set; }
        public string fechaEntrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mueble Mueble { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
