//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public int idMueble { get; set; }
        public Nullable<double> monto { get; set; }
        public string fecha { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
